Dev-Ops-2021-Customers/customers

service/routes.py
tests/test_routes.py

Updated routes.py and test_routes.py files for read-customer

Updated read-customer code

---

service/routes.py
tests/test_models.py
tests/test_routes.py

Added update-customer code to routes and test files

Added update-customer to routes and test files

---

tests/test_models.py
tests/test_routes.py

Added test coverage for sad path requests to both tests_models.py and tests_routes.py.

Added test coverage to model and routes

---

travis.yml

added travis.yml file for Travis CI

added travis.yml file

---

service/models.py
service/routes.py
tests/test_models.py
tests/test_routes.py

Danielle and I worked on this story together. We added the "active" status as true when creating customers and added code to deactivate the user. We also added tests to test_routes and test_models.

Added "Active" status and ability to deactivate

---

tests/test_models.py

Added a test for find by name in the model. The model for find by name was already there.

Added test for find by name in model

---

service/routes.py
tests/test_routes.py

completing query for find by name

Added a find by name method and related test case

---

Procfile
Vagrantfile
config.py
manifest.yml
requirements.txt

Updated the necessary files to manually push the app to cloud foundry and utilize the Elephant SQL database. Also included the requirement for Honcho.

Updates to manually push the app to the cloud and connect the db

---

service/static/index.html
service/static/js/rest_api.js

Also made some updates to the customer.id code in routes.py file

Added query functionality and search button

---

service/static/index.html
service/static/js/rest_api.js

Updated index.html and rest_api.js to include the UI changes to support activate and deactivate.

added activate and deactive UI

---

Vagrantfile
features/customers.feature
features/environment.py
features/steps/customer_steps.py
requirements.txt

Created feature folder with environment.py, customer_steps.py and customers.feature. We also modified vagrant file and requirements.txt. This code is needed for the remaining bdd stories.

Bdd create

---

service/static/js/rest_api.js

deleted "/deactivate" from the delete code in rest_api.js

updated rest_api to fix delete bug

---

features/customers.feature

added retrieve BDD test case and updated delete test case to mimic ID language

Bdd retrieve 2

---

requirements.txt
service/routes.py

Adds the API documentation docstrings for each API method. CRUD, list/query, activate, deactivate. Also adds flasgger.

API Documentation with flassger for customer service

---

.travis.yml

Updated travis.yml to include bdd tests in the file. This will help us with our CI pipeline

Updated travis.yml file to include bdd tests

---

features/environment.py
manifest.yml

The Test stage is failing in the CI pipeline so I increased the wait time and memory to help

Increased wait time to 500 and memory to 256

---

features/steps/customer_steps.py
manifest.yml

updated memory in manifest and commented out screenshot debug step in deactivate scenario

Update memory and deactivate scenario

---

features/steps/customer_steps.py

added context before WAIT_SECONDS for bdd tests

added context before WAIT_SECONDS for bdd tests

---

features/customers.feature
features/environment.py
features/steps/customer_steps.py

Updated wait time and deactive and activate steps.

updated wait time to 600 and updated the deactivate and active steps

---

manifest-prod.yml

added manifest-prod.yml file with prod URL

added prod manifest yml file
